### ISSUE TITLE
Pipeline component asks for the reference Microsoft.XLANGs.BaseTypes

### ISSUE THREAD

**Issue by msjonathan** [CoditEU/Mjolnir#33] opened 2015-12-04 15:48 UTC
When using the base pipeline component, the reference to XLANG base types is asked.
This is because the BizTalk.Extended.Core has a reference to this dll. 

Is this wanted behavior? - maybe this could be solved with my previous ticket. #31

**Comment by tomkerkhove** [comment] 2015-12-04 15:55
#31 should not fix it - It should only add the pipeline dlls for pipelines and vice versa imo.

What in Core is using this?

**Comment by msjonathan** [comment] 2015-12-04 16:03
MessageContextPropertyBase is part of this assembly.

**Comment by tomkerkhove** [comment] 2015-12-04 16:07
A-ha, It's because of ContextPropertySerializer.

We'll have to take a look at how we can abstract it or move some stuff around.

Good catch!

**Comment by tomkerkhove** [comment] 2016-02-18 18:32
This is not a bug since it is a mandatory reference for what we're doing.
Closing this issue.

**Closed by tomkerkhove** 2016-02-18 18:32 UTC
Labels: bug
